language: python
python: "3.6"

jobs:
  include:
    - stage: Test
      install:
        - pip install codecov

      script:
        - coverage run -m unittest discover src --verbose
        - coverage report -m

      after_success:
        - codecov