language: python
python: "3.6"

install: pip install codecov

stages:
  - Test

jobs:
  include:
    - stage: Deploy
      script: python -m unittest discover ./src --verbose
      after_success: codecov